---
project: 10FoD Traditional
kind: PIPELINE
name: bitnami-artifactory
enabled: true
description: Pipeline to deploy bitnami-artifactory to aws
concurrency: 10
ciWorkspace:
  endpoint: ''
  image: ''
  registry: ''
  path: ''
  cache:
  - ''
stageOrder:
- Stage0
stages:
  Stage0:
    taskOrder:
    - Task0
    tasks:
      Task0:
        type: Blueprint
        endpoints:
          gitServer: vra-content
        input:
          blueprint: ''
          filepath: blueprints/bitnami-artifactory/blueprint.yaml
          action: CreateDeployment
          deploymentName: ''
          version: ''
          parameters: {
            user: vmware,
            sshkey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBqa/DVGZYsvga24xAEnFDpBUGuip43qcw81uVPqEIoL5rRDmrfEOfR/Wg9hMDLQgOtmjX5n2Y83WYIjadscvXygwyZhWUiYL8UvOqDdFtCkWoD0DFkmTttld4fFETCvNdRMJtnfGmQRhc9zMdeIS6BGoe/66INKmVfNyfKfHhd7SeJ/UQmsu8yVeA6bpWhz0/bG/+H50Gs2Zpba/16UF2e4PJ7hah167mO+ZkHAtNIumcaM9SOxE4eUSTItajOTEXgnKV3XtloyRrdNikwj2fBr5QzTCEn8afpg7/Sv1YchfS5SZdJfR4sJbh0bNlYQNTiXoHK/YxhoTpZq7bVArT,
            hostname1: bitnami-artifactory,
            SelectCloud: 'env:aws'
          }
notifications:
  email:
  - subject: bitnami-artifactory deployment
    endpoint: Codestream-Default-Email
    event: SUCCESS
    body: Deployment notification for bitnami-artifactory
    to:
    - wirthj@vmware.com
