---
project: 10FoD Traditional
kind: PIPELINE
name: coreos-docker-host
enabled: false
description: Pipeline to deploy coreos-docker-host to aws
concurrency: 10
ciWorkspace:
  endpoint: ''
  image: ''
  registry: ''
  path: ''
  cache:
  - ''
stageOrder:
- Stage0
stages:
  Stage0:
    taskOrder:
    - Task0
    tasks:
      Task0:
        type: Blueprint
        endpoints:
          gitServer: vra-content
        input:
          blueprint: ''
          filepath: blueprints/coreos-docker-host/blueprint.yaml
          action: CreateDeployment
          deploymentName: ''
          version: ''
          parameters: {
            user: vmware,
            sshkey: '${var.ssh-cloud-pub-key}',
            hostname1: coreos-docker-host,
            SelectCloud: 'env:aws'
          }
notifications:
  email:
  - event: SUCCESS
    subject: coreos-docker-host deployment
    endpoint: Codestream-Default-Email
    body: Deployment notification for coreos-docker-host
    to:
    - wirthj@vmware.com
