---
project: 10FoD Traditional
kind: PIPELINE
name: pulse-build
enabled: true
description: Pipeline to deploy pulse-build to aws
concurrency: 10
ciWorkspace:
  endpoint: ''
  image: ''
  registry: ''
  path: ''
  cache:
  - ''
stageOrder:
- Stage0
stages:
  Stage0:
    taskOrder:
    - Task0
    tasks:
      Task0:
        type: Blueprint
        endpoints:
          gitServer: vra-content
        input:
          blueprint: ''
          filepath: blueprints/pulse-build/blueprint.yaml
          action: CreateDeployment
          deploymentName: ''
          version: ''
          parameters: {
            user: vmware,
            sshkey: ${var.ssh-cloud-pub-key},
            hostname1: pulse-build,
            SelectCloud: 'env:aws'
          }
notifications:
  email:
  - subject: pulse-build deployment
    endpoint: Codestream-Default-Email
    event: SUCCESS
    body: Deployment notification for pulse-build
    to:
    - wirthj@vmware.com
