---
project: 10FoD Traditional
kind: PIPELINE
name: pulse-build
enabled: true
concurrency: 10
options: [
  DOCKER_TRIGGER]
ciWorkspace:
  endpoint: docker-host-aws
  image: jameswwirth/vra-ci-task
  registry: docker-hub-vra-ci-task
  path: ''
  cache:
  - ''
stageOrder:
- Stage0
stages:
  Stage0:
    taskOrder:
    - Task0
    tasks:
      Task0:
        type: CI
        input:
          process: [
            ]
          steps: [
            '#!/bin/bash',
            apt-get install -y git,
            mkdir ~/.ssh/,
            cat <<EOT>> ~/.ssh/id_rsa.pub,
            '${var.github-deploy-public-key}',
            EOT,
            'cat <<EOT>> ~/.ssh/id_rsa ',
            '${var.github-deploy-private-key}',
            '# cat  ~/.ssh/id_rsa.pub',
            '# cat  ~/.ssh/id_rsa',
            cat <<EOT>> ~/.ssh/config,
            Host *,
            '    StrictHostKeyChecking no',
            chmod 600 ~/.ssh/id_rsa,
            chmod 600 ~/.ssh/id_rsa.pub,
            '# eval "$(ssh-agent -s)"',
            '# ssh-add -k ~/.ssh/id_rsa',
            'mkdir pulse-package ',
            cd pulse-package,
            'wget https://iotc005.vmware.com/api/iotc-cli/package-cli.zip',
            unzip package-cli.zip,
            chmod 755 linux_amd64/package-cli,
            'git clone git@github.com:jameswwirth/people-counter-ingestion-service.git',
            cd people-counter-ingestion-service/build,
            ls,
            ../../linux_amd64/package-cli package create ../build/people-counter-ingestion-service-spec.yml,
            '../../linux_amd64/package-cli upload package people_counter_ingestion_service-1.0.0.iotcp
              https://iotc005.vmware.com',
            '']
          export: [
            ]
          artifacts: [
            ]
